/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    InfoPanel: typeof import('./components/InfoPanel.vue')['default']
    MapView: typeof import('./components/MapView.vue')['default']
    PanoramaModal: typeof import('./components/PanoramaModal.vue')['default']
  }
}
